spring:
  application:
    name: schema-msg
  profiles:
    active: default, dev

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/admin
      auto-index-creation: true


  # JACKSON configurations
  jackson:
    # default name strategy
    # PropertyNamingStrategy[*LOWER_CAMEL_CASE*, SNAKE_CASE, UPPER_CAMEL_CASE, LOWER_CASE, KEBAB_CASE, LOWER_DOT_CASE]
    #spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
    property-naming-strategy: LOWER_CAMEL_CASE
    # ignore null properties in the serialization, similar to @JsonInclude(JsonInclude.Include.NON_NULL)
    default-property-inclusion: non_null
    deserialization:
      # Throw an exception if an unknown propriety arrives in the request body, the default value is false
      fail-on-unknown-properties: true
      # throw an exception if a property annotated with @JsonIgnore arrives in the request body, the default value is false
      fail-on-ignored-properties: true
    serialization:
      write-bigdecimal-as-plain: true


## Actuator
### $ curl localhost:8082/actuator/health -d {} -H "Content-Type: application/json"
management:
  security:
    enabled: false
  endpoints:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG

mongock:
  enabled: true
  #change-logs-scan-package: io.github.jlmc.mongodbschemamsg.infrastructure.dbmigrations
  migration-scan-package: io.github.jlmc.mongodbschemamsg.infrastructure.dbmigrations
  index-creation: true
  # runner-type: ApplicationRunner
  #transaction-enabled: true
